// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwo4GWcrhffmyu_tS8-VMj7olKKm7WOwA',
    appId: '1:1070896115791:web:a17cc2674208aa7f1f3a3a',
    messagingSenderId: '1070896115791',
    projectId: 'vehicle-84f51',
    authDomain: 'vehicle-84f51.firebaseapp.com',
    storageBucket: 'vehicle-84f51.firebasestorage.app',
    measurementId: 'G-2H4EH2SRJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRqmvfFlUpKiHJvaLbPwa_LoMWmFnREEs',
    appId: '1:1070896115791:android:c4034c46a04e13621f3a3a',
    messagingSenderId: '1070896115791',
    projectId: 'vehicle-84f51',
    storageBucket: 'vehicle-84f51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLlucAXGLjMdDRQUcFmRx2JL3t37VG-v8',
    appId: '1:1070896115791:ios:b9ce8c04c867cd5a1f3a3a',
    messagingSenderId: '1070896115791',
    projectId: 'vehicle-84f51',
    storageBucket: 'vehicle-84f51.firebasestorage.app',
    iosBundleId: 'com.example.vehicle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwo4GWcrhffmyu_tS8-VMj7olKKm7WOwA',
    appId: '1:1070896115791:web:c5c36879e36891731f3a3a',
    messagingSenderId: '1070896115791',
    projectId: 'vehicle-84f51',
    authDomain: 'vehicle-84f51.firebaseapp.com',
    storageBucket: 'vehicle-84f51.firebasestorage.app',
    measurementId: 'G-TFZJ80863X',
  );
}
